-- Credits to gadiiell_
local optimization = true
local function coolopt()
   if optimization == true then
    console.set_int( "r_3dsky", 0 )
    console.set_int( "r_shadows", 0 )
    console.set_int( "cl_csm_static_prop_shadows", 0 )
    console.set_int( "cl_csm_shadows", 0 )
    console.set_int( "cl_csm_world_shadows", 0 )
    console.set_int( "cl_foot_contact_shadows", 0 )
    console.set_int( "cl_csm_viewmodel_shadows", 0 )
    console.set_int( "cl_csm_rope_shadows", 0 )
    console.set_int( "cl_csm_sprite_shadows", 0 )
    console.set_int( "cl_disablefreezecam", 0 )
    console.set_int( "cl_freezecampanel_position_dynamic", 0 )
    console.set_int( "cl_freezecameffects_showholiday", 0 )
    console.set_int( "cl_showhelp", 0 )
    console.set_int( "cl_autohelp", 0 )
    console.set_int( "cl_disablehtmlmotd", 0 )
    console.set_int( "mat_postprocess_enable", 0 )
    console.set_int( "fog_enable_water_fog", 0 )
    console.set_int( "gameinstructor_enable", 0 )
    console.set_int( "cl_csm_world_shadows_in_viewmodelcascade", 0 )
    console.set_int( "cl_disable_ragdolls", 0 )
    client.log("::  RusWare has appeared! It just increased your RAM therefore your FPS!")
    optimization = false
    end
end
local function unload()
    console.set_int( "r_3dsky", 1 )
    console.set_int( "r_shadows", 1 )
    console.set_int( "cl_csm_static_prop_shadows", 1 )
    console.set_int( "cl_csm_shadows", 1 )
    console.set_int( "cl_csm_world_shadows", 1 )
    console.set_int( "cl_foot_contact_shadows", 1 )
    console.set_int( "cl_csm_viewmodel_shadows", 1 )
    console.set_int( "cl_csm_rope_shadows", 1 )
    console.set_int( "cl_csm_sprite_shadows", 1 )
    console.set_int( "cl_disablefreezecam", 1 )
    console.set_int( "cl_freezecampanel_position_dynamic", 1 )
    console.set_int( "cl_freezecameffects_showholiday", 1 )
    console.set_int( "cl_showhelp", 1 )
    console.set_int( "cl_autohelp", 1 )
    console.set_int( "cl_disablehtmlmotd", 1 )
    console.set_int( "mat_postprocess_enable", 1 )
    console.set_int( "fog_enable_water_fog", 1 )
    console.set_int( "gameinstructor_enable", 1 )
    console.set_int( "cl_csm_world_shadows_in_viewmodelcascade", 1 )
    console.set_int( "cl_disable_ragdolls", 1 )   
end
cheat.RegisterCallback("unload", unload)
cheat.RegisterCallback("on_paint", coolopt)
